-- CreateEnum
CREATE TYPE "CategoriaRendicionGasto" AS ENUM ('MATERIALES_SUMINISTROS', 'TRANSPORTES', 'ACTIVOS_FIJOS', 'MANTENIMIENTO_SERVICIOS', 'OBLIGACIONES_SOCIALES', 'OBRAS_CONSTRUCCION', 'GASTOS_ADMINISTRATIVOS', 'OTROS_GASTOS_ADMINISTRATIVOS', 'OTROS', 'MEDIO_AMBIENTE');

-- AlterTable
ALTER TABLE "GastoCaja" ADD COLUMN     "categoriaRendicion" "CategoriaRendicionGasto" NOT NULL DEFAULT 'OTROS';
